okpy and otter
data-8/zero-to-data-8 pull request #47
Opened 2020-04-28 21:45 UTC by chrispyles

2020-04-28 23:32 UTC, alexnakagawa requested changes

2020-04-28 23:32 UTC, alexnakagawa commented on content/v2/tech/autograding/okpy.md
> +After you have created the notebook, continue by making an assignment on [okpy.org](https://okpy.org) and generating a .ok file that is used to configure the autograding client. The .ok file is place
```suggestion
After you have created the notebook, continue by making an assignment on [okpy.org](https://okpy.org) and generating a `.ok` file that is used to configure the autograding client. The `.ok` file is placed in a public GitHub repo with the student notebook and any support files (e.g. data files), which students will pull into their JupyterHub accounts to work on.
```

2020-04-28 23:32 UTC, alexnakagawa commented on content/v2/tech/autograding/okpy.md
> +One advantage here is that this experience is (almost) entirely within the notebook and students don't need to worry about donwloading and uploading files.
Are there any disadvantages to this?

2020-04-28 23:32 UTC, alexnakagawa commented on content/v2/tech/autograding/otter.md
> +* **Otter Assign** is a fork of [OkPy's jassign](https://github.com/okpy/jassign) that allows instructors to create a master notebook containing questions, solutions, and tests and parses them into a
```suggestion
* **Otter Assign** is a fork of [OkPy's jassign](https://github.com/okpy/jassign) that allows instructors to create a master notebook containing questions, solutions, and tests and parses them into autograder and student's distribution versions of notebooks. It fully integrates with the other Otter tools, e.g. allowing instructors to generate an autograding file for Gradescope as a part of the Assign process.
```

2020-04-28 23:32 UTC, alexnakagawa commented on content/v2/tech/autograding/otter.md
> +* **Otter Grader** is the core original functionality of Otter that allows instructors to grade student submissions locally in sandboxed Docker containers. This tool supports submission export format
```suggestion
* **Otter Grader** is the core functionality of Otter that allows instructors to grade student submissions locally in sandboxed Docker containers. This tool supports submission export formats from Learning Management Systems (LMS) like [Gradescope](https://www.gradescope.com/) and [Canvas](https://www.instructure.com/) and returns to instructors a CSV of grades for each submission. Optionally, the instructor can opt for a generated filterable PDF of each submission for manual grading.
```

2020-04-29 00:29 UTC, chrispyles commented on content/v2/tech/autograding/okpy.md
> +One advantage here is that this experience is (almost) entirely within the notebook and students don't need to worry about donwloading and uploading files.
from the student's perspective? no

2020-04-29 00:30 UTC, chrispyles commented on content/v2/tech/autograding/otter.md
> +* **Otter Assign** is a fork of [OkPy's jassign](https://github.com/okpy/jassign) that allows instructors to create a master notebook containing questions, solutions, and tests and parses them into a
I think it's correctly worded the way it is

2020-04-29 00:34 UTC, alexnakagawa approved these changes

2020-04-29 00:34 UTC, merged